# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Evaluation of the retrieval system"
# Optionally set API keys here instead of exporting environment variables.
# Never commit real keys to source control.
# env:
#   OPENAI_API_KEY: sk-...
prompts:
  - "{{ query }}"

providers:
  - file://provider.ts

tests:
  ## Sticks to provided context to answer the question (Context adherence test)
  - vars:
      query: What prereqs should I have before studying JavaScript?
    assert:
      - type: context-faithfulness
        transform: "output.answer"
        contextTransform: "output.context"
        value: |
          - A general understanding of the Internet and the World Wide Web (WWW)
          - Good working knowledge of HyperText Markup Language (HTML)
          - Some programming experience.
          For more details see [refer to the Introduction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction)
        threshold: 0.9 # Require 90% of claims to be supported

  ## Always links to the provided context
  - vars:
      query: What's the example used in the MDN docs to demonstrate how to declare a variable?
    assert:
      - type: contains
        transform: "output.answer"
        value: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#declaring_variables
