# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Evaluation of the retrieval system"
# Optionally set API keys here instead of exporting environment variables.
# Never commit real keys to source control.
# env:
#   OPENAI_API_KEY: sk-...
prompts:
  - "{{ query }}"

providers:
  - file://retreival-provider.ts

tests:
  - vars:
      query: What's the example used in the MDN docs to demonstrate how to declare a variable?
    assert:
      - type: contains-all
        value:
          - grammar_and_types/index.md_chunk_7
          - language_overview/index.md_chunk_14
